#158: implement calculate average stars and forks for repos
zerocracy/judges-action pull request #172
Opened 2024-07-28 18:34 UTC by Yegorov

2024-07-28 18:47 UTC, yegor256 requested changes
looks like a typo to me

2024-07-28 18:47 UTC, yegor256 commented on judges/quality-of-service/simple-collect.yml
> +  - /fb/f[average_build_success_rate != 0]
@Yegorov two times the same line. typo?

2024-07-28 18:51 UTC, Yegorov commented on judges/quality-of-service/simple-collect.yml
> +  - /fb/f[average_build_success_rate != 0]
@yegor256 Yes, a typo, did not notice

2024-07-28 19:13 UTC, yegor256 commented
@rultor merge

2024-07-28 19:24 UTC, merged

2024-07-28 19:24 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/42786-2254616581) (took me 8min)

2024-07-28 19:28 UTC, yegor256 commented
@Yegorov thanks!

2024-07-28 20:08 UTC, 0crat commented
@Yegorov Thanks for the review! You've earned +5 points for this: +25 as a basis; -40 for reviewing your own contribution; +20 to give you at least something.

2024-07-28 21:07 UTC, 0crat commented
@Yegorov Thanks for the contribution! You've earned +20 points. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+5](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

2024-08-10 13:20 UTC, 0crat commented
@yegor256 Hello! Thank you for your code review. As per our team policy, you've earned +15 points: +25 base points, with a -10 deduction due to the low number of comments (only 2). While we appreciate your effort, more detailed feedback would be valuable for the team. Your current balance stands at [-581](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work, and remember that providing thorough comments can boost your points in future reviews!