#193: calculate average release hoc and commits size
zerocracy/judges-action pull request #336
Opened 2024-09-14 19:53 UTC by Yegorov

Closes #193

2024-09-14 19:55 UTC, Yegorov commented
@Suban05 please review. Test fail, because this https://github.com/zerocracy/fbe/pull/95 PR need merge before

2024-09-15 12:01 UTC, Suban05 requested changes
@Yegorov looks good, but see some the comment

2024-09-15 12:01 UTC, Suban05 commented on judges/quality-of-service/quality-of-service.rb
> +  repo_releses = {}
@Yegorov typo? `repo_releases`?

2024-09-15 12:09 UTC, Yegorov commented on judges/quality-of-service/quality-of-service.rb
> +  repo_releses = {}
@Suban05 Yes, of course, thanks, fixed!

2024-09-15 12:15 UTC, Suban05 approved these changes
@Yegorov 👍

2024-09-15 12:16 UTC, Yegorov commented
@yegor256 please check

2024-09-15 13:02 UTC, merged

2024-09-15 13:36 UTC, 0crat commented
@Suban05 Great job on the review! You've earned +4 points: +4 base, -10 for limited comments, but +10 to recognize your effort. Your commitment shines through! 🌟 Current balance: [+250](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work!

<!-- Thanks for the review! You've earned +4 points for this: +4 as a basis; -10 for very few (4) comments; +10 to give you at least something.  Your running balance is [+250](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).  -->

2024-09-15 14:32 UTC, 0crat commented
@Yegorov 🎉 Great work on your contribution! You've earned +10 points: +4 base, +9 for 196 hits-of-code, -4 for limited comments. [Keep up](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the momentum! Your balance is now [+170](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Looking forward to your next submission!

<!-- Thanks for the contribution! You've earned +10 points for this: +4 as a basis; +9 for the 196 hits-of-code that you wrote; -4 for very few (4) comments. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+170](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).  -->